### ISSUE TITLE
Logic on whether to power cycle wi-fi is reversed

### ISSUE THREAD

**Issue by ssctrevor2** [acodega/macos#2]
Line 25: if [ "$activeWiFiNetwork" = "$wifiNetwork" ]; then

This statement evaluates whether the active network is identical to the network being deleted, but then if true states that they're not the same. Put an exclamation point before the = in order to evaluate as false to get the desired result.

revised: if [ "$activeWiFiNetwork" != "$wifiNetwork" ]; then

**Comment by acodega** [comment]
Thanks for the catch. I updated the code.
